const webpackConfigBase = require("./webpack.config.base.js");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const Dotenv = require("dotenv-webpack");
const path = require("path");
const devProxy = require("./devProxy.js");

module.exports = {
  ...webpackConfigBase,

  mode: "development",
  output: {
    ...webpackConfigBase.output,
    chunkFilename: "chunks/[name].chunk.js",
  },
  optimization: {
    splitChunks: {
      chunks: "all",
    },
  },
  devServer: {
    static: {
      directory: path.join(process.cwd(), "./build"),
    },
    port: 2409,
    hot: true,
    compress: true,
    historyApiFallback: true,
    proxy: devProxy,
  },
  plugins: [
    ...webpackConfigBase.plugins,
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "src/index.html",
    }),
    new Dotenv({
      path: path.join(process.cwd(), "/.env.development"),
    }),
  ],
  devtool: "eval-source-map",
  performance: {
    hints: false,
  },
};
